const assert = require('node:assert/strict');
const fs = require('node:fs');
const {lowercaseExcept, remapSelection} = require('../web/case-tools.js');
assert.equal(lowercaseExcept('Привет Иван из МОСКВЫ!', new Set([1, 3])), 'привет Иван из МОСКВЫ!');
assert.equal(lowercaseExcept('ЁЛКА  ИВАН\tNASA', new Set([1, 2])), 'ёлка  ИВАН\tNASA');
assert.equal(lowercaseExcept('Москва Москва', new Set([1])), 'москва Москва');
assert.equal(lowercaseExcept('ИМЯ', new Set()), 'имя');
assert.equal(lowercaseExcept('Имя ФАМИЛИЯ', new Set([0, 1])), 'Имя ФАМИЛИЯ');
assert.equal(lowercaseExcept('', new Set()), '');
assert.deepEqual([...remapSelection('Это Иван', 'Вот Это Иван', new Set([1]))], [2]);
assert.deepEqual([...remapSelection('Это Иван', 'Это Игорь', new Set([1]))], [1]);
assert.deepEqual([...remapSelection('Это Иван', 'Это', new Set([1]))], []);
const html = fs.readFileSync(require.resolve('../web/index.html'), 'utf8');
const editor = fs.readFileSync(require.resolve('../web/editor.js'), 'utf8');
new Function(editor);
for (const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g)) new Function(match[1]);
assert.ok(!html.includes('hlColorPicker'));
assert.ok(editor.includes('const lines = rows.map(r => ({ text: r.text }));'));
console.log('Case operations, selection remapping and inline script syntax: OK');
assert.equal((editor.match(/\/\/ Глобальный обработчик Cmd\+Z/g) || []).length, 1);
